path: /content/drive/MyDrive/Licenta/ExDetectUsa  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train # val images (relative to 'path')

# Classes
names:
  0: Door_NoDamage
  1: Door_Damage
  2: No_Door